travis:
  secure:
    BINSTAR_TOKEN: L+ZmGZZbRUdWkuACnKEpPWklb0q9aWjNwOTzhUyJieB5CiwZ/0WTaQqbAJ19CRoe0bUr6YnAWYDhPAsFYYWAUmaKFER5exTVb9m7NQ31rKrdR2XVmwAOivhuelyzwU63JKUtpEkNx69rtoa4IADDtEMtGEYj+v+JgMAxbJDpD/PKM2KWMKrJ2OzA88j2wPXfZo6oc1IL8gSC3RTpWD27JnNel0scXkmKYL5qKCko9rXyvw/cvM5Tk9JVFfGf7G/f/xZNlKYiVQlHIByrsfaBVs0gb77vDOTn63Ag0IITypzx0iGJd8bhzQrye56Q0DxSv79BiP2IDv5LL3E79s4jS2eP20rkoJpVh5tyIL7/la5NGOiCzcRMIrGo7PiGGMpItkUAhyVmqFaxKnBnqIJhwCEZieBjs26C+1DbArCbpQsEjQPj+etP2kwDvaIZ+fAU6NOJ9XhP6uBYE0TIctojjyImoheH2PeOuhlvSLkrS2/tg8Y1DIkcIymSX9jZA6tOsYnoTVfNOqAMsMdFHh6LceEePHK8HyBwHKmzzriOy8bEtPzwH0jDHO8cXZq6Zb6SWiLbNED9m69jjW4ppa1wNTAWGCeX55s6h+vFEiE3f821qXNyk10HRLGPQfJKrGVTNWcEQR2kS2pO1c+eWUzSs3pRH2Kxhug/GWj8LWBFC1E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
